<a href="https://colab.research.google.com/github/Mundiamercy/BCS-03-0037-2026/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Uploading the file

In [2]:
from google.colab import files
uploaded = files.upload()

Saving manufacturing_dataset_.xlsx to manufacturing_dataset_ (1).xlsx

#Import Libraries

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_excel("manufacturing_dataset_.xlsx")

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#Display Headings

In [7]:
df.head()

,Product_ID,Factory,Production_Line,Machine_Type,Shift,Operator_Experience,Training_Hours,Machine_Age,Maintenance_Frequency,Production_Hours,Raw_Material_Quality,Energy_Consumption,Temperature,Humidity,Defect_Rate,Production_Cost
0,P00001,kisumu,B,Conveyor,Night,1.2,63.4,1.2,7.0,12.4,69.6,585.7,19.3,61.1,12.46,11042.34
1,P00002,Nairobi,D,CNC,Morning,2.9,18.5,6.5,11.0,7.6,83.3,647.2,26.2,60.1,13.94,12379.05
2,P00003,Mombasa,D,Conveyor,Evening,7.2,33.6,4.0,4.0,5.6,72.0,546.6,25.6,54.7,11.69,10374.77
3,P00004,Nakuru,B,Robotic,Morning,19.2,13.9,11.4,6.0,10.8,74.0,547.7,35.5,33.8,13.42,10958.11
4,P00005,Nairobi,A,Robotic,Night,8.9,87.4,17.8,6.0,4.5,78.5,317.6,20.6,33.2,12.69,6793.83

# Display information

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Product_ID             1020 non-null   object
 1   Factory                1014 non-null   object
 2   Production_Line        1015 non-null   object
 3   Machine_Type           1012 non-null   object
 4   Shift                  1015 non-null   object
 5   Operator_Experience    1017 non-null   float64
 6   Training_Hours         1010 non-null   float64
 7   Machine_Age            1017 non-null   float64
 8   Maintenance_Frequency  1014 non-null   float64
 9   Production_Hours       1016 non-null   float64
 10  Raw_Material_Quality   1014 non-null   float64
 11  Energy_Consumption     1008 non-null   float64
 12  Temperature            1017 non-null   float64
 13  Humidity               1016 non-null   float64
 14  Defect_Rate            1019 non-null   float64
 15  Production_Cost        1017 non-null   float64
dtypes: float64(11), object(5)
memory usage: 127.6+ KB

# Check for misssing values

In [9]:
df.isnull().sum()

Product_ID                0
Factory                   6
Production_Line           5
Machine_Type              8
Shift                     5
Operator_Experience       3
Training_Hours           10
Machine_Age               3
Maintenance_Frequency     6
Production_Hours          4
Raw_Material_Quality      6
Energy_Consumption       12
Temperature               3
Humidity                  4
Defect_Rate               1
Production_Cost           3
dtype: int64

#Handle the null by dropping

In [10]:
df = df.dropna(subset=["Production_Cost"])

#Define X and Y

In [11]:
y = df["Production_Cost"]

X = df.drop(columns=["Production_Cost","Product_ID"])

#Filling missing numerical values

In [12]:
num_cols = X.select_dtypes(include=["int64","float64"]).columns

X[num_cols] = X[num_cols].fillna(X[num_cols].mean())

#Filling missing categorical values

In [13]:
cat_cols = X.select_dtypes(include=["object"]).columns

for col in cat_cols:
    X[col] = X[col].fillna(X[col].mode()[0])

#Comfirming with a null value is still present

In [16]:
df.isnull().sum()

Product_ID                0
Factory                   6
Production_Line           5
Machine_Type              8
Shift                     5
Operator_Experience       3
Training_Hours           10
Machine_Age               3
Maintenance_Frequency     6
Production_Hours          4
Raw_Material_Quality      6
Energy_Consumption       12
Temperature               3
Humidity                  4
Defect_Rate               1
Production_Cost           0
dtype: int64

In [17]:
X = pd.get_dummies(X, drop_first=True)

#Split into training and testing data

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y,
test_size=0.20,random_state=42)

#Build the model

In [20]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [21]:
print(model.intercept_)

1074.3204820859519

In [40]:
coefficients = pd.DataFrame({
    "Variable": X.columns,
    "Coefficient": model.coef_
})

coefficients

                  Variable  Coefficient
0      Operator_Experience    -3.192185
1           Training_Hours    -1.956030
2              Machine_Age    53.951707
3    Maintenance_Frequency     1.209558
4         Production_Hours     9.589231
5     Raw_Material_Quality    -7.563212
6       Energy_Consumption    17.990404
7              Temperature     3.960272
8                 Humidity    -0.261957
9              Defect_Rate    -8.705563
10        Factory_ Mombasa  -147.655289
11        Factory_ Nairobi   -78.738727
12         Factory_ Nakuru  -232.413406
13          Factory_Kisumu  -143.115248
14         Factory_Kisumu    196.688125
15         Factory_Mombasa   -84.159987
16        Factory_Mombasa   -193.791397
17         Factory_NAIROBI   -59.696865
18         Factory_Nairobi   -72.606483
19        Factory_Nairobi   -158.592832
20          Factory_Nakuru  -135.179126
21         Factory_Nakuru    -74.937054
22          Factory_kisumu  -117.101804
23         Factory_mombasa  -121.029287
24         Factory_nairobi   -55.518247
25          Factory_nakuru   -76.775889
26       Production_Line_B   -21.295812
27       Production_Line_C   -44.538016
28       Production_Line_D   -91.568433
29   Machine_Type_Conveyor     3.227100
30  Machine_Type_Hydraulic    31.044595
31    Machine_Type_Robotic   -42.978853
32          Shift_ Morning   130.179290
33            Shift_ Night   -43.107348
34           Shift_Evening    58.055707
35          Shift_Evening     55.759478
36           Shift_Morning    59.084855
37          Shift_Morning    244.294684
38             Shift_Night    49.867192
39            Shift_Night     33.523658
40           Shift_evening   112.510716
41           Shift_morning   249.076043
42             Shift_night    38.041942

In [45]:
for feature, coef in zip(X.columns, model.coef_):
    print(f"{feature}: {coef}")

Operator_Experience: -3.1921851269465136
Training_Hours: -1.9560299599191193
Machine_Age: 53.951706826287854
Maintenance_Frequency: 1.2095579607165519
Production_Hours: 9.589230797062452
Raw_Material_Quality: -7.5632117147397695
Energy_Consumption: 17.990404122228256
Temperature: 3.960272490458073
Humidity: -0.26195727891884696
Defect_Rate: -8.705562554611978
Factory_ Mombasa: -147.65528924834928
Factory_ Nairobi: -78.73872663198172
Factory_ Nakuru: -232.41340567738396
Factory_Kisumu: -143.1152482966362
Factory_Kisumu : 196.6881254859745
Factory_Mombasa: -84.1599869332386
Factory_Mombasa : -193.79139735520326
Factory_NAIROBI: -59.69686497428203
Factory_Nairobi: -72.6064834969473
Factory_Nairobi : -158.59283245050008
Factory_Nakuru: -135.1791263001166
Factory_Nakuru : -74.93705432178602
Factory_kisumu: -117.10180398304867
Factory_mombasa: -121.02928728091858
Factory_nairobi: -55.51824695262907
Factory_nakuru: -76.77588894246718
Production_Line_B: -21.295812376343306
Production_Line_C: -44.53801628030359
Production_Line_D: -91.5684334709926
Machine_Type_Conveyor: 3.227100084046471
Machine_Type_Hydraulic: 31.044595144882766
Machine_Type_Robotic: -42.978852608012645
Shift_ Morning: 130.17929044484794
Shift_ Night: -43.10734786585912
Shift_Evening: 58.05570703829165
Shift_Evening : 55.75947762375685
Shift_Morning: 59.08485548048258
Shift_Morning : 244.29468441303396
Shift_Night: 49.86719155879057
Shift_Night : 33.52365840981146
Shift_evening: 112.51071572265828
Shift_morning: 249.07604330366706
Shift_night: 38.04194172958736

#Make predictions

In [25]:
y_pred = model.predict(X_test)

Evaluate the model

In [41]:
MAE= mean_absolute_error(y_test, y_pred)

In [47]:
print("mae:", MAE)

mae: 201.40636047667118

In [48]:
MSE = mean_squared_error(y_test, y_pred)
print("mse:", MSE)

mse: 177938.29103399153

In [49]:
RMSE= np.sqrt(MSE)
print("rmse:", RMSE)

rmse: 421.82732371669755

In [50]:
R2 = r2_score(y_test, y_pred)
print("r²:", R2)

r²: 0.9872217634353